# 標準SWA設定
experiment:
  name: "standard_swa"
  output_dir: "out/standard_swa"
  csv_name: "standard_swa_log.csv"

training:
  epochs: 200
  learning_rate: 0.1
  weight_decay: 0.0005
  momentum: 0.9
  optimizer: "Adam"

swa:
  method: "swa"
  start_ratio: 0.75
  interval: 1
  swa_lr: 0.01

dataset:
  batch_size: 64
  num_workers: 2

logging:
  log_dir: "./log"
