# しきい値SWA（マスキング）設定
experiment:
  name: "threshold_swa_masking"
  output_dir: "out/threshold_swa_masking"
  csv_name: "threshold_swa_masking_log.csv"

training:
  epochs: 200
  learning_rate: 0.1
  weight_decay: 0.0005
  momentum: 0.9
  optimizer: "Adam"

swa:
  method: "threshold_swa"
  start_ratio: 0.75
  interval: 1
  swa_lr: 0.01

threshold_swa:
  threshold: "mean+1std"
  mode: "gt"  # しきい値より大きいパラメータを選択
  selection_type: "threshold"
  update_type: "masking"
  topk_ratio: 0.1

dataset:
  batch_size: 64
  num_workers: 2

logging:
  log_dir: "./log"

debug:
  enabled: true
  print_mask_ratios: true
  print_weight_stats: false
